### ISSUE TITLE
Create Minutes of Meeting for the Meeting Held on July 4th, 2023

### ISSUE THREAD

**Issue by Sagar7421** [Sagar7421/Eureka-Soen6011summer2023#1]
We need to create minutes of the meeting that took place on July 4th, 2023. The minutes serve as an official record of the meeting, capturing the discussions, decisions, and action items.

**Comment by anuragagarwal6895** [comment]
Hello all,

I have already documented and added it as a wiki page document. 

Below is the link for the same : 
[Minutes of Meeting for the Meeting Held on July 4th, 2023 ](https://github.com/Sagar7421/Eureka-Soen6011summer2023/wiki/Minutes-of-Meeting-4th-July,-2023)
